# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow-old.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 638)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/swiss-marketing-knife.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    font-weight: bold;\n"
"}\n"
"QLabel{font-weight: bold;}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tab_widget.setFont(font)
        self.tab_widget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tab_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.le_match = QtWidgets.QLineEdit(self.tab)
        self.le_match.setObjectName("le_match")
        self.horizontalLayout_7.addWidget(self.le_match)
        self.btn_match = QtWidgets.QPushButton(self.tab)
        self.btn_match.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_match.setObjectName("btn_match")
        self.horizontalLayout_7.addWidget(self.btn_match)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.btn_import = QtWidgets.QPushButton(self.tab)
        self.btn_import.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_import.setObjectName("btn_import")
        self.verticalLayout_8.addWidget(self.btn_import)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_match_importing_update = QtWidgets.QLabel(self.tab)
        self.lbl_match_importing_update.setObjectName("lbl_match_importing_update")
        self.verticalLayout_7.addWidget(self.lbl_match_importing_update)
        self.pb_import_update = QtWidgets.QProgressBar(self.tab)
        self.pb_import_update.setProperty("value", -1)
        self.pb_import_update.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_import_update.setObjectName("pb_import_update")
        self.verticalLayout_7.addWidget(self.pb_import_update)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_matching_update = QtWidgets.QLabel(self.tab)
        self.lbl_matching_update.setObjectName("lbl_matching_update")
        self.verticalLayout_9.addWidget(self.lbl_matching_update)
        self.pb_match_update = QtWidgets.QProgressBar(self.tab)
        self.pb_match_update.setEnabled(True)
        self.pb_match_update.setProperty("value", -1)
        self.pb_match_update.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_match_update.setObjectName("pb_match_update")
        self.verticalLayout_9.addWidget(self.pb_match_update)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_11.addItem(spacerItem3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_match = QtWidgets.QLabel(self.tab)
        self.lbl_match.setEnabled(True)
        self.lbl_match.setObjectName("lbl_match")
        self.verticalLayout_10.addWidget(self.lbl_match)
        self.pb_match_camp = QtWidgets.QProgressBar(self.tab)
        self.pb_match_camp.setEnabled(True)
        self.pb_match_camp.setProperty("value", -1)
        self.pb_match_camp.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_match_camp.setObjectName("pb_match_camp")
        self.verticalLayout_10.addWidget(self.pb_match_camp)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem4)
        self.tab_widget.addTab(self.tab, "")
        self.tab_update = QtWidgets.QWidget()
        self.tab_update.setObjectName("tab_update")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_update)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_upd_choose = QtWidgets.QLabel(self.tab_update)
        self.lbl_upd_choose.setObjectName("lbl_upd_choose")
        self.verticalLayout_2.addWidget(self.lbl_upd_choose)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_upd_files = QtWidgets.QComboBox(self.tab_update)
        self.cb_upd_files.setMinimumSize(QtCore.QSize(175, 0))
        self.cb_upd_files.setObjectName("cb_upd_files")
        self.horizontalLayout_2.addWidget(self.cb_upd_files)
        self.btn_dl_update = QtWidgets.QPushButton(self.tab_update)
        self.btn_dl_update.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_dl_update.setObjectName("btn_dl_update")
        self.horizontalLayout_2.addWidget(self.btn_dl_update)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.lbl_downloading_update = QtWidgets.QLabel(self.tab_update)
        self.lbl_downloading_update.setObjectName("lbl_downloading_update")
        self.verticalLayout_2.addWidget(self.lbl_downloading_update)
        self.pb_download_update = QtWidgets.QProgressBar(self.tab_update)
        self.pb_download_update.setProperty("value", -1)
        self.pb_download_update.setObjectName("pb_download_update")
        self.verticalLayout_2.addWidget(self.pb_download_update)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.tab_widget.addTab(self.tab_update, "")
        self.tab_match = QtWidgets.QWidget()
        self.tab_match.setObjectName("tab_match")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_match)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_match_choose = QtWidgets.QLabel(self.tab_match)
        self.lbl_match_choose.setObjectName("lbl_match_choose")
        self.verticalLayout_3.addWidget(self.lbl_match_choose)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_files = QtWidgets.QComboBox(self.tab_match)
        self.cb_files.setMinimumSize(QtCore.QSize(175, 0))
        self.cb_files.setObjectName("cb_files")
        self.horizontalLayout_3.addWidget(self.cb_files)
        self.btn_dl_match = QtWidgets.QPushButton(self.tab_match)
        self.btn_dl_match.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_dl_match.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_dl_match.setObjectName("btn_dl_match")
        self.horizontalLayout_3.addWidget(self.btn_dl_match)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.lbl_downloading_match = QtWidgets.QLabel(self.tab_match)
        self.lbl_downloading_match.setObjectName("lbl_downloading_match")
        self.verticalLayout_3.addWidget(self.lbl_downloading_match)
        self.pb_download_match = QtWidgets.QProgressBar(self.tab_match)
        self.pb_download_match.setProperty("value", -1)
        self.pb_download_match.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_download_match.setObjectName("pb_download_match")
        self.verticalLayout_3.addWidget(self.pb_download_match)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.lbl_match_importing_match = QtWidgets.QLabel(self.tab_match)
        self.lbl_match_importing_match.setObjectName("lbl_match_importing_match")
        self.verticalLayout_3.addWidget(self.lbl_match_importing_match)
        self.pb_import_match = QtWidgets.QProgressBar(self.tab_match)
        self.pb_import_match.setProperty("value", -1)
        self.pb_import_match.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_import_match.setObjectName("pb_import_match")
        self.verticalLayout_3.addWidget(self.pb_import_match)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.lbl_campaign = QtWidgets.QLabel(self.tab_match)
        self.lbl_campaign.setEnabled(True)
        self.lbl_campaign.setObjectName("lbl_campaign")
        self.verticalLayout_3.addWidget(self.lbl_campaign)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.le_campaign = QtWidgets.QLineEdit(self.tab_match)
        self.le_campaign.setEnabled(False)
        self.le_campaign.setMaximumSize(QtCore.QSize(175, 16777215))
        self.le_campaign.setText("")
        self.le_campaign.setObjectName("le_campaign")
        self.horizontalLayout_4.addWidget(self.le_campaign)
        self.btn_match_old = QtWidgets.QPushButton(self.tab_match)
        self.btn_match_old.setEnabled(False)
        self.btn_match_old.setMinimumSize(QtCore.QSize(75, 0))
        self.btn_match_old.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_match_old.setObjectName("btn_match_old")
        self.horizontalLayout_4.addWidget(self.btn_match_old)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.tab_widget.addTab(self.tab_match, "")
        self.tab_cross = QtWidgets.QWidget()
        self.tab_cross.setObjectName("tab_cross")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_cross)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_upd_choose_2 = QtWidgets.QLabel(self.tab_cross)
        self.lbl_upd_choose_2.setObjectName("lbl_upd_choose_2")
        self.verticalLayout_4.addWidget(self.lbl_upd_choose_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb_cross_files = QtWidgets.QComboBox(self.tab_cross)
        self.cb_cross_files.setMinimumSize(QtCore.QSize(175, 0))
        self.cb_cross_files.setMaximumSize(QtCore.QSize(175, 16777215))
        self.cb_cross_files.setObjectName("cb_cross_files")
        self.horizontalLayout_5.addWidget(self.cb_cross_files)
        self.btn_dl_cc = QtWidgets.QPushButton(self.tab_cross)
        self.btn_dl_cc.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_dl_cc.setObjectName("btn_dl_cc")
        self.horizontalLayout_5.addWidget(self.btn_dl_cc)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.lbl_downloading_cc = QtWidgets.QLabel(self.tab_cross)
        self.lbl_downloading_cc.setObjectName("lbl_downloading_cc")
        self.verticalLayout_4.addWidget(self.lbl_downloading_cc)
        self.pb_download_cc = QtWidgets.QProgressBar(self.tab_cross)
        self.pb_download_cc.setProperty("value", -1)
        self.pb_download_cc.setObjectName("pb_download_cc")
        self.verticalLayout_4.addWidget(self.pb_download_cc)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.lbl_process_cc = QtWidgets.QLabel(self.tab_cross)
        self.lbl_process_cc.setObjectName("lbl_process_cc")
        self.verticalLayout_4.addWidget(self.lbl_process_cc)
        self.pb_process_cc = QtWidgets.QProgressBar(self.tab_cross)
        self.pb_process_cc.setProperty("value", -1)
        self.pb_process_cc.setObjectName("pb_process_cc")
        self.verticalLayout_4.addWidget(self.pb_process_cc)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.lbl_upload_cc = QtWidgets.QLabel(self.tab_cross)
        self.lbl_upload_cc.setObjectName("lbl_upload_cc")
        self.verticalLayout_4.addWidget(self.lbl_upload_cc)
        self.pb_upload_cc = QtWidgets.QProgressBar(self.tab_cross)
        self.pb_upload_cc.setProperty("value", -1)
        self.pb_upload_cc.setObjectName("pb_upload_cc")
        self.verticalLayout_4.addWidget(self.pb_upload_cc)
        spacerItem21 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem21)
        self.tab_widget.addTab(self.tab_cross, "")
        self.tab_autoscale = QtWidgets.QWidget()
        self.tab_autoscale.setObjectName("tab_autoscale")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_autoscale)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wv_autoscale = QtWebKitWidgets.QWebView(self.tab_autoscale)
        self.wv_autoscale.setStyleSheet("")
        self.wv_autoscale.setUrl(QtCore.QUrl("about:blank"))
        self.wv_autoscale.setObjectName("wv_autoscale")
        self.verticalLayout_5.addWidget(self.wv_autoscale)
        self.tab_widget.addTab(self.tab_autoscale, "")
        self.tab_top_fifty = QtWidgets.QWidget()
        self.tab_top_fifty.setObjectName("tab_top_fifty")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_top_fifty)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_garments = QtWidgets.QComboBox(self.tab_top_fifty)
        self.cb_garments.setMinimumSize(QtCore.QSize(150, 0))
        self.cb_garments.setObjectName("cb_garments")
        self.horizontalLayout.addWidget(self.cb_garments)
        self.lbl_dt_from = QtWidgets.QLabel(self.tab_top_fifty)
        self.lbl_dt_from.setObjectName("lbl_dt_from")
        self.horizontalLayout.addWidget(self.lbl_dt_from)
        self.de_from = QtWidgets.QDateEdit(self.tab_top_fifty)
        self.de_from.setCalendarPopup(True)
        self.de_from.setObjectName("de_from")
        self.horizontalLayout.addWidget(self.de_from)
        self.label = QtWidgets.QLabel(self.tab_top_fifty)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.de_to = QtWidgets.QDateEdit(self.tab_top_fifty)
        self.de_to.setCalendarPopup(True)
        self.de_to.setObjectName("de_to")
        self.horizontalLayout.addWidget(self.de_to)
        self.btn_top_fifty = QtWidgets.QPushButton(self.tab_top_fifty)
        self.btn_top_fifty.setObjectName("btn_top_fifty")
        self.horizontalLayout.addWidget(self.btn_top_fifty)
        spacerItem22 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.tbl_top_fifty = QtWidgets.QTableWidget(self.tab_top_fifty)
        self.tbl_top_fifty.setObjectName("tbl_top_fifty")
        self.tbl_top_fifty.setColumnCount(5)
        self.tbl_top_fifty.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_fifty.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_fifty.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_fifty.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_fifty.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_top_fifty.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tbl_top_fifty)
        self.tab_widget.addTab(self.tab_top_fifty, "")
        self.verticalLayout.addWidget(self.tab_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Swiss Marketing Knife"))
        self.label_3.setText(_translate("MainWindow", "Choose File:"))
        self.btn_match.setText(_translate("MainWindow", "..."))
        self.btn_import.setText(_translate("MainWindow", "Import"))
        self.lbl_match_importing_update.setText(_translate("MainWindow", "Importing:"))
        self.lbl_matching_update.setText(_translate("MainWindow", "Matching DMC ID\'s with Email:"))
        self.lbl_match.setText(_translate("MainWindow", "Matching DMC ID and Email with Campaigns:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.lbl_upd_choose.setText(_translate("MainWindow", "Please choose file from below:"))
        self.btn_dl_update.setText(_translate("MainWindow", "Download"))
        self.lbl_downloading_update.setText(_translate("MainWindow", "Downloading:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_update), _translate("MainWindow", "Update Subs w DMCIDs"))
        self.lbl_match_choose.setText(_translate("MainWindow", "Please choose file from below:"))
        self.btn_dl_match.setText(_translate("MainWindow", "Start"))
        self.lbl_downloading_match.setText(_translate("MainWindow", "Downloading:"))
        self.lbl_match_importing_match.setText(_translate("MainWindow", "Importing:"))
        self.lbl_campaign.setText(_translate("MainWindow", "Enter Campaign:"))
        self.le_campaign.setPlaceholderText(_translate("MainWindow", "Enter Campaign"))
        self.btn_match_old.setText(_translate("MainWindow", "Match"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_match), _translate("MainWindow", "Find Subs in DM List"))
        self.lbl_upd_choose_2.setText(_translate("MainWindow", "Please choose file from below:"))
        self.btn_dl_cc.setText(_translate("MainWindow", "Download"))
        self.lbl_downloading_cc.setText(_translate("MainWindow", "Downloading:"))
        self.lbl_process_cc.setText(_translate("MainWindow", "Processing File:"))
        self.lbl_upload_cc.setText(_translate("MainWindow", "Uploading File:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_cross), _translate("MainWindow", "Export for Cross Country"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_autoscale), _translate("MainWindow", "Auto Scale"))
        self.lbl_dt_from.setText(_translate("MainWindow", "From:"))
        self.label.setText(_translate("MainWindow", "To:"))
        self.btn_top_fifty.setText(_translate("MainWindow", "View"))
        item = self.tbl_top_fifty.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SKU"))
        item = self.tbl_top_fifty.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Design"))
        item = self.tbl_top_fifty.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Orders"))
        item = self.tbl_top_fifty.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pieces"))
        item = self.tbl_top_fifty.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sales"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_top_fifty), _translate("MainWindow", "Top Fifty"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

from PyQt5 import QtWebKitWidgets
import resource_rc
